GET / HTTP/1.1
Host: news.ycombinator.com


###

GET / HTTP/1.1
Host: example.com

###

POST / HTTP/1.1
Host: example.com
Content-Type: application/json

{
    "key": "value"
}

###

GET https://pokeapi.co/api/v2/pokemon HTTP/1.1 Content-Type: application/json


###


GET https://pokeapi.co/api/v2/pokemon/13/ HTTP/1.1 Content-Type: application/json

### 
https://pokeapi.co/api/v2/pokemon?offset=25&limit=12

### 
https://pokeapi.co/api/v2/item
### 
https://pokeapi.co/api/v2/item/2/
### 
https://pokeapi.co/api/v2/ability?offset=50
### 
https://pokeapi.co/api/v2/ability/15/


###
DELETE  https://pokeapi.co/api/v2/pokemon/13/ HTTP/1.1 Content-Type: application/json

###

GET http://localhost:8080/sighting HTTP/1.1 Accept: application/json


###

GET /sighting/2 HTTP/1.1
Host: localhost:8080
Accept: application/json



###
POST http://localhost:8080/sighting HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "bugType": "Mosquito",
  "description": "mosquitos are jerks",
  "date": "2020-07-04",
  "interest": 0.0
}


###
PUT http://localhost:8080/sighting/2 HTTP/1.1
Content-Type: application/json

{ "sightingId": 2, "bugType": "Cicada", "description": "the cicadas are singing in the trees", "date": "2020-09-24", "interest": 9.245 }


###

DELETE http://localhost:8080/sighting/3 HTTP/1.1

###

POST http://localhost:8080/sighting HTTP/1.1
Content-Type: application/json
Accept: application/json

{
  "bugType": "Cockroach",
  "description": "cockroaches are dirty",
  "date": "2024-07-04",
  "interest": 1.0
}


###
PUT http://localhost:8080/sighting/2 HTTP/1.1
Content-Type: application/json

{ "sightingId": 5, "bugType": "not cockraoch", "description": "the cockraochers are singing in the trees", "date": "2020-09-24", "interest": 9.245 }


###
GET http://localhost:8080/get HTTP/1.1

###
POST http://localhost:8080/post HTTP/1.1

###
PUT http://localhost:8080/put HTTP/1.1

###
DELETE http://localhost:8080/delete HTTP/1.1

###
OPTIONS http://localhost:8080/multi HTTP/1.1

###
POST /add/2/6 HTTP/1.1 
Host: localhost:8080

###
GET /product/house paint/more/path HTTP/1.1 
Host: localhost:8080


###
POST /pets HTTP/1.1 
Host: localhost:8080 
Content-Type: application/json 

{ "name": "Gibby", "type": "Cat" }

###
PUT /pets/9 HTTP/1.1 
Host: localhost:8080 
Content-Type: application/json 

{ "petId": 9, "name": "Midge", "type": "Pug" }


###
PUT /pets/9 HTTP/1.1 
Host: localhost:8080 
Content-Type: application/json 

{ "nope": "nah" }

###
POST http://localhost:8080/urlencoded HTTP/1.1 
Content-Type: application/x-www-form-urlencoded 

name=Yuki&age=24&likesCookies=true

###
POST /post HTTP/1.1 
Host: localhost:8080 
Content-Type: application/json 

{ "petId": 9, "name": "Midge", "type": "Pug" }


###
PUT /put HTTP/1.1 
Host: localhost:8080 
Content-Type: application/json 

{ "petId": 15, "name": "Midge", "type": "Pug" }

###
PUT /put HTTP/1.1 
Host: localhost:8080 
Content-Type: application/json 

{ "petId": 15, "name": "Midge", "type": "Pug" }
